### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by pedroluisvsousa** [Probesys/glpi-plugins-groupcategory#1]
Hi,
I unzipped the file in the ./plugins directory but the plugin did not appear in the glpi interface.

**Comment by pVesian** [comment]
Hello @pedroluisvsousa. Have you renamed the directory to `groupcategory`?

**Comment by pedroluisvsousa** [comment]
Sure!  I also edited the permissions for the directory.
But the problem persists. I'm using GLPI 9.2.3.

**Comment by pVesian** [comment]
I'm going to need more details then. Please paste here what appears on Setup -> General -> System -> Information about system installation and configuration.

**Comment by pedroluisvsousa** [comment]
Following screens..,

![configuracoes_glpi](https://user-images.githubusercontent.com/26510405/41356078-6e350d20-6ef9-11e8-85cc-2191a36c7f39.png)

![glpi_interface_web](https://user-images.githubusercontent.com/26510405/41356089-793701e2-6ef9-11e8-89a9-f9efbb86f7c9.png)

![terminal_plugin](https://user-images.githubusercontent.com/26510405/41356098-802a6976-6ef9-11e8-9e97-3feaa3266e34.png)

**Comment by pVesian** [comment]
It seems I forgot to commit a very important file. Please add the contents of this link in a setup.php file in the root of the plugin: https://raw.githubusercontent.com/Probesys/glpi-plugins-groupcategory/master/setup.php
The next release will of course include this file.

**Comment by pedroluisvsousa** [comment]
Great!!! That's ok!
