### ISSUE TITLE
Problème affichage dans ticket v1.2.3

### ISSUE THREAD

**Issue by benshoes** [Probesys/glpi-plugins-groupcategory#10]
GLPI 9.4.4
Bonjour,
A la création d'un ticket le choix de la catégorie fonctionne sans problème et l'attribue correctement au ticket.
Par contre, au niveau affichage, la 1ère catégorie de la liste est affichée et reprise à chaque enregistrement.
Ce qui est dérangent car il faut vérifier et remettre la catégorie à chaque fois que l'on veut éditer le ticket.
Cordialement,

**Comment by mab18** [comment]
Hi,
I see the same thing and more : the first category is selected BUT this is not the good one.
If we correct the category, it is recorded, but the first one is displayed again.
I don't know why.

**Comment by felag** [comment]
Bonjour,
@benshoes  Est-ce que ce problème est toujours d'actualité en version 1.4.0RC3 ?

@mab18 Do you still have this issue with release 1.4.0RC3 ?

**Comment by felag** [comment]
Sans réponse après 10 mois: je ferme.
