### ISSUE TITLE
Problème changement de la catégorie v 1.2.3

### ISSUE THREAD

**Issue by cedricdemeulder** [Probesys/glpi-plugins-groupcategory#11]
Bonjour,
J'ai le plugin version 1.2.3 sous GLPI 9.4.5.
Si je modifie un ticket (ajout suivi par exemple), la catégorie est modifiée et passe sur la première de la liste.
Cette réaction provoque des exécutions en chaîne de règles et notification...
Serait-il possible de corriger ce problème ?
Cordialement.

**Comment by felag** [comment]
Bonjour,

est-ce que ce problème est toujours visible pour vous avec la version 1.4.0RC3 et GLPI 9.5 ?

Cordialement,

**Comment by philg38** [comment]
Bonjour,
sans réponse à notre commentaire et cette remontée ayant été la seule, nous cloturons ce ticket que nous ne parvenons pas à répéter sur la version 1.4
