### ISSUE TITLE
GLPI 9.5.X Porting ?

### ISSUE THREAD

**Issue by benshoes** [Probesys/glpi-plugins-groupcategory#14]
Hello,
I would like to know if a port was going to be done for the 9.5.X version ?
Best regards,

**Comment by felag** [comment]
Hello,

We released [version 1.4.0RC3](https://github.com/Probesys/glpi-plugins-groupcategory/releases/tag/v1.4.0RC3) that is GLPI 9.5.X compatible.

Regards,
