### ISSUE TITLE
problem in version 10

### ISSUE THREAD

**Issue by ts2050** [Probesys/glpi-plugins-groupcategory#17]
I tried to install the plugin, but the screen is all white.

glpi version: 10.0.5

**Comment by ctresvaux** [comment]
Hi
What version of the plugin you tried to install ?

**Comment by ctresvaux** [comment]
Can you try to install the latest release please (v1.5.0)  ?
I've fixed the setup

**Comment by ts2050** [comment]
Hello, 

I am sorry for late, I am Brazil {timezone}.

Now, it's working

Regards

**Comment by ctresvaux** [comment]
ok thank you for your feeback
