### ISSUE TITLE
Error in simplified interface

### ISSUE THREAD

**Issue by veimarlopezsalazar** [Probesys/glpi-plugins-groupcategory#19]
I am using the plugin in a GLPI 10.0.7 installation, and for users belonging to a group that uses the simplified interface, it does not allow selecting the category when creating a ticket. Thank you for your assistance.

**Comment by philg38** [comment]
I @veimarlopez ,
i have test the plugin on 1.5.1 version to try to repeat your problem
i have add a profil to one user to use the simplified interface and add this user to group with limitation by the groupcategory plugin.
The categories selector is correctly replace and populate on the simplified interface for this user.
 For me all is ok si i close this issue.
You can test with the last version of the plugin and if you have always problem open a new issue.
