### ISSUE TITLE
Problem when the category list is large

### ISSUE THREAD

**Issue by pedroluisvsousa** [Probesys/glpi-plugins-groupcategory#2]
Hello,
I noticed a problem when the category list is large.
After scrolling the drop-down list, when you go to select the category, the list goes back to the start.

**Comment by pVesian** [comment]
Hi @pedroluisvsousa. With how many categories does this occur and with which browser? A fix might not be easy to find since it's a normal selection list. The browsers make up the rules. But I will look into it.

**Comment by pedroluisvsousa** [comment]
I tried with Firefox and Chrome.

**Comment by pedroluisvsousa** [comment]
Video about this issue.

https://www.dropbox.com/s/rv88a5iusqp3g2s/out-2.ogv?dl=0

**Comment by pVesian** [comment]
Thanks. I'm not really sure how to fix this, I will look into it.

**Comment by lucioaquino** [comment]
> Video about this issue.
> 
> https://www.dropbox.com/s/rv88a5iusqp3g2s/out-2.ogv?dl=0

Salve Pedro 

Este Plugin  está funcionando pra você ? qual versão está usando ?

This Plugin is working for you ? Which Version do you use ?

**Comment by felag** [comment]
Hello,

we believe that this problem is resolved with version 1.4.0RC3 and GLPI 9.5.

Can you please confirm ?

Regards,

**Comment by philg38** [comment]
No confirm message and answer,
