### ISSUE TITLE
Erreur lors de l'activation en ligne de commandes

### ISSUE THREAD

**Issue by felag** [Probesys/glpi-plugins-groupcategory#21]
Lorsque j'utilise la commande `bin/console plugin:activate groupcategory` pour activer le plugin, cela ne fonctionne pas et les messages suivants s'affichent:

```
Plugin "groupcategory" activation failed.
Plugin GroupCategory is not CSRF compliant!
```

Il est possible de contourner l'erreur en activant le plugin sur l'interface web (dans `Configuration` → `Plugins`).

Il serait bienvenu de pouvoir activer ce plugin depuis la ligne de commandes.

**Comment by philg38** [comment]
corrigé par commit 56af407f2daf0db6402cc3d6044619a2e4bcf2dd
