### ISSUE TITLE
Problems v1.2.2

### ISSUE THREAD

**Issue by hawatius** [Probesys/glpi-plugins-groupcategory#9]
Groupcategory v1.2.2

1. Child categories cannot be selected.
2. In the created tickets, all categories are visible.
3. It is not possible to change the category in an existing ticket (not an administrator)
_You don't have permission to perform this action._

**Comment by philg38** [comment]
hi,
actualy only allowed categories are display on the select.
the last commit  fixe the second point
i can't repeat the last point

**Comment by hawatius** [comment]
Hi.
In the created tickets, all categories are visible -  fixe 1.2.3
last point, all is well, that was my mistake.

There remains a problem with the choice of categories, it is possible to select only the first category.

And yet, the plugin changes the display of categories, can this be fixed?
![Снимок экрана в 2019-09-18 08-55-30](https://user-images.githubusercontent.com/19649806/65118261-8c8f6980-d9f3-11e9-8535-d244eced8d13.png)
![Снимок экрана в 2019-09-18 08-55-10](https://user-images.githubusercontent.com/19649806/65118278-8ef1c380-d9f3-11e9-983c-d45bbce7822a.png)

**Comment by felag** [comment]
Hello,
we believe that this issue is resolve with release 1.4.0RC3 and GLPI 9.5.
Can you confirm ?

Regards,

**Comment by philg38** [comment]
No confirm message and answer,
